// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Todo) Parent(ctx context.Context) (*Todo, error) {
	result, err := _m.Edges.ParentOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryParent().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Todo) Children(ctx context.Context) (result []*Todo, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedChildren(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ChildrenOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryChildren().All(ctx)
	}
	return result, err
}

func (_m *Todo) Owner(ctx context.Context) (*User, error) {
	result, err := _m.Edges.OwnerOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryOwner().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *User) Todos(ctx context.Context) (result []*Todo, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTodos(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TodosOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTodos().All(ctx)
	}
	return result, err
}
